### ISSUE TITLE
Bois, PR #20 is broke af

### ISSUE THREAD

**Issue by Sv443** [Academy-Of-Animu/Coding-Yabe-Sei#21]
#20 is broken and it's basically this: 
![picture](https://user-images.githubusercontent.com/38158426/54774729-abf83600-4c0c-11e9-9712-b2eab223b976.png)

**Comment by IllusionMan1212** [comment]
This isn't issue worthy :squint:

**Comment by Sv443** [comment]
no u

**Comment by Sv443** [comment]
whomst are closing this

**Comment by Sv443** [comment]
fix the damn
