### ISSUE TITLE
Fluff command is down toooo

### ISSUE THREAD

**Issue by ctsstc** [Academy-Of-Animu/Coding-Yabe-Sei#26]
Seems that `https://api-to.get-a.life/` is down and gone.
I'm not sure if there's any replacement for such magic unfortunately  : \

This site seems to be the savior again, they seem to have some random animal images we can tap into
https://some-random-api.ml/

**Comment by canarado** [comment]
https://some-random-api.ml seems like a decent replacement

**Comment by ctsstc** [comment]
har har just was updating my comment with that ;D
It's the new hot goodness on the market right now
I will make them famous or bring them to their knees `¯\_(ツ)_/¯`
